-- Alinha valores do enum ListingType com a API (JOB_VACANCY / PROFESSIONAL_PROFILE)
ALTER TYPE "ListingType" RENAME VALUE 'BICO' TO 'JOB_VACANCY';
ALTER TYPE "ListingType" RENAME VALUE 'PRODUTO' TO 'PROFESSIONAL_PROFILE';
